using System.Text.Json.Serialization;

namespace VOCENuOrderApp.Models.XoroModels
{
    public class XoroProduct
    {
    }

    //Custom Product details
    public class ProductDetails
    {
        public string BasePart { get; set; }
        public string Season { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public string ItemNumber { get; set; }
        public string NuSkuId { get; set; }
        public bool PreSellFlag { get; set; }
        public string SizeName { get; set; }
        public string SizeCode { get; set; }
        public string PreBookAvailableFrom { get; set; }
        public string PreBookAvailableTo { get; set; }
        public string FutureAvailableFrom { get; set; }
        public string FutureAvailableTo { get; set; }
        public string NuOrderId { get; set; }
        public string NuOrderBrandId { get; set; }
        public bool Presell { get; set; }
    }


    // Xoro Create Product Object
    public class XoroCreateProductRoot
    {
        public List<BasePartA> BaseProductData { get; set; }
    }

    public class BasePartA
    {
        public string BodyHtml { get; set; }
        public string BasePartNumber { get; set; }
        public string Handle { get; set; }
        public string ProductCategoryName { get; set; }
        public string Title { get; set; }
        public List<ProductOptionA> Options { get; set; }
        public bool ActiveFlag { get; set; }
        public List<ProductVariantA> Variants { get; set; }
    }

    public class ProductOptionA
    {
        public string Name { get; set; }
        public int Position { get; set; }
        public List<ProductValueA> Values { get; set; }
        public List<string> ValueArr { get; set; }
    }

    public class ProductValueA
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public int Seq { get; set; }
    }

    public class ProductVariantA
    {
        public string ItemNumber { get; set; }
        public string Description { get; set; }
        public string ItemBarcode { get; set; }
        public string HSCode { get; set; }
        public string CooCodeIso2 { get; set; }
        public string ItemUpc { get; set; }
        public string Tags { get; set; }
        public bool IsTaxableFlag { get; set; }
        public string IsTaxableFlagStr { get; set; }
        public bool IsSellableFlag { get; set; }
        public string IsSellableFlagStr { get; set; }
        public bool IsPurchasableFlag { get; set; }
        public string IsPurchasableFlagStr { get; set; }
        public bool IsRawMaterialFlag { get; set; }
        public string IsRawMaterialFlagStr { get; set; }
        public bool ManufactureItemFlag { get; set; }
        public string ManufactureItemFlagStr { get; set; }
        public bool IsTransferableFlag { get; set; }
        public string IsTransferableFlagStr { get; set; }
        public bool IsPreSellFlag { get; set; }
        public string IsPreSellFlagStr { get; set; }
        public string ItemTypeName { get; set; }
        public bool IsBomItemFlag { get; set; }
        public string SellUomName { get; set; }
        public decimal? StandardUnitPrice { get; set; }
        public string AssetAccountName { get; set; }
        public string CogsAccountName { get; set; }
        public string AdjAccountName { get; set; }
        public string IncomeAccountName { get; set; }
        public string IncomeReturnAccountName { get; set; }
        public string ExpenseAccountName { get; set; }
        public string WipAccountName { get; set; }
        public string SizeUomName { get; set; }
        public string WeightUomName { get; set; }
        public decimal? StandardUnitCost { get; set; }
        public string ImagePath { get; set; }
        public bool UpdateDefaultItemImage { get; set; }
        public string SeasonValues { get; set; }
        public float? Weight { get; set; }
        public object Length { get; set; }
        public object Width { get; set; }
        public object Height { get; set; }
        public string AlertNote { get; set; }
        public string WebUrl { get; set; }
        public string HazmatName { get; set; }
        public decimal? SellPkgQty { get; set; }
        //public int ReOrderPointQty { get; set; }
        //public int ReOrderQty { get; set; }
        public bool ActiveFlag { get; set; }
        public string ActiveFlagStr { get; set; }
        public string AlternativeItemNumber1 { get; set; }
        public string AlternativeItemNumber2 { get; set; }
        public string AlternativeItemNumber3 { get; set; }
        public string SaleTaxCode { get; set; }
        public string PurchaseTaxCode { get; set; }
        public string BrandName { get; set; }
        public string GroupName { get; set; }
        public string GenderCode { get; set; }
        public string CategoryName { get; set; }
        public string SubCategoryName { get; set; }
        public bool ReturnableFlag { get; set; }
        public string ReturnableFlagStr { get; set; }
        public bool IsTaxableOnSale { get; set; }
        public string IsTaxableOnSaleStr { get; set; }
        public bool IsTaxableOnPurchase { get; set; }
        public string IsTaxableOnPurchaseStr { get; set; }
        public string SalesNotes { get; set; }
        public string PurchaseNotes { get; set; }
        public string Option1Value { get; set; }
        public string Option1Code { get; set; }
        public string Option2Value { get; set; }
        public string Option2Code { get; set; }
        public string Option3Value { get; set; }
        public string Option3Code { get; set; }
        public List<ProductCurrencypricelistA> CurrencyPriceList { get; set; }
        public string DefaultVendorName { get; set; }
        public string MaterialName { get; set; }
        public decimal? CustomPrice1 { get; set; }
        public decimal? CustomPrice10 { get; set; }
        public decimal? CustomPrice11 { get; set; }
        public decimal? CustomPrice12 { get; set; }
        public decimal? CustomPrice13 { get; set; }
        public decimal? CustomPrice14 { get; set; }
        public decimal? CustomPrice2 { get; set; }
        public decimal? CustomPrice3 { get; set; }
        public decimal? CustomPrice4 { get; set; }
        public decimal? CustomPrice5 { get; set; }
        public decimal? CustomPrice6 { get; set; }
        public decimal? CustomPrice7 { get; set; }
        public decimal? CustomPrice8 { get; set; }
        public decimal? CustomPrice9 { get; set; }
        public string CustomFieldH1 { get; set; }
        public string CustomFieldH10 { get; set; }
        public string CustomFieldH11 { get; set; }
        public string CustomFieldH12 { get; set; }
        public string CustomFieldH13 { get; set; }
        public string CustomFieldH14 { get; set; }
        public string CustomFieldH15 { get; set; }
        public string CustomFieldH16 { get; set; }
        public string CustomFieldH17 { get; set; }
        public string CustomFieldH18 { get; set; }
        public string CustomFieldH19 { get; set; }
        public string CustomFieldH2 { get; set; }
        public string CustomFieldH20 { get; set; }
        public string CustomFieldH21 { get; set; }
        public string CustomFieldH22 { get; set; }
        public string CustomFieldH23 { get; set; }
        public string CustomFieldH24 { get; set; }
        public string CustomFieldH25 { get; set; }
        public string CustomFieldH26 { get; set; }
        public string CustomFieldH27 { get; set; }
        public string CustomFieldH28 { get; set; }
        public string CustomFieldH29 { get; set; }
        public string CustomFieldH3 { get; set; }
        public string CustomFieldH30 { get; set; }
        public string CustomFieldH31 { get; set; }
        public string CustomFieldH32 { get; set; }
        public string CustomFieldH33 { get; set; }
        public string CustomFieldH34 { get; set; }
        public string CustomFieldH35 { get; set; }
        public string CustomFieldH36 { get; set; }
        public string CustomFieldH37 { get; set; }
        public string CustomFieldH38 { get; set; }
        public string CustomFieldH39 { get; set; }
        public string CustomFieldH4 { get; set; }
        public string CustomFieldH40 { get; set; }
        public string CustomFieldH41 { get; set; }
        public string CustomFieldH42 { get; set; }
        public string CustomFieldH43 { get; set; }
        public string CustomFieldH44 { get; set; }
        public string CustomFieldH45 { get; set; }
        public string CustomFieldH46 { get; set; }
        public string CustomFieldH47 { get; set; }
        public string CustomFieldH48 { get; set; }
        public string CustomFieldH49 { get; set; }
        public string CustomFieldH5 { get; set; }
        public string CustomFieldH50 { get; set; }
        public string CustomFieldH6 { get; set; }
        public string CustomFieldH7 { get; set; }
        public string CustomFieldH8 { get; set; }
        public string CustomFieldH9 { get; set; }

    }

    public class ProductCurrencypricelistA
    {
        public string CurrencyCode { get; set; }
        public decimal? CustomPrice1 { get; set; }
        public decimal? CustomPrice10 { get; set; }
        public decimal? CustomPrice11 { get; set; }
        public decimal? CustomPrice12 { get; set; }
        public decimal? CustomPrice13 { get; set; }
        public decimal? CustomPrice14 { get; set; }
        public decimal? CustomPrice2 { get; set; }
        public decimal? CustomPrice3 { get; set; }
        public decimal? CustomPrice4 { get; set; }
        public decimal? CustomPrice5 { get; set; }
        public decimal? CustomPrice6 { get; set; }
        public decimal? CustomPrice7 { get; set; }
        public decimal? CustomPrice8 { get; set; }
        public decimal? CustomPrice9 { get; set; }
        public string ItemNumber { get; set; }
        public decimal? StandardUnitCost { get; set; }
        public decimal? StandardUnitPrice { get; set; }
    }




    // Xoro Get Product Object
    public class XoroGetProductRoot
    {
        public bool ConfirmFlag { get; set; }
        public object ConfirmValue { get; set; }
        public object ConfirmValueData { get; set; }
        public List<XoroProductDatum> Data { get; set; }
        public bool EndRequest { get; set; }
        public int ErrorCode { get; set; }
        public bool IsForwardRequest { get; set; }
        public bool LogFlag { get; set; }
        public string Message { get; set; }
        public object MessageTitle { get; set; }
        public string MetaData { get; set; }
        public bool Result { get; set; }
    }

    public class XoroProductDatum
    {
        public int Id { get; set; }
        public string BodyHtml { get; set; }
        public string Handle { get; set; }
        public string BasePartNumber { get; set; }
        //public int CategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public string Title { get; set; }
        public List<ProductOption> Options { get; set; }
        public bool ActiveFlag { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public List<ProductVariant> Variants { get; set; }
        public object[] ProductImages { get; set; }
    }

    public class ProductOption
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public string[] ValueArr { get; set; }
        public List<ProductValue> Values { get; set; }
    }

    public class ProductValue
    {
        public string Code { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int OptionId { get; set; }
        public int Seq { get; set; }
    }

    public class ProductVariant
    {
        public bool ActiveFlag { get; set; }
        public object ActiveFlagStr { get; set; }
        //public string AdjAccntId { get; set; }
        public string AdjAccountName { get; set; }
        public string AlertNote { get; set; }
        public bool AllowBackorderFlag { get; set; }
        public object AllowedPurchaseUomIdList { get; set; }
        public object AllowedPurchaseUomNameList { get; set; }
        public object AllowedSellUomIdList { get; set; }
        public object AllowedSellUomNameList { get; set; }
        public string AlternativeItemNumber1 { get; set; }
        public string AlternativeItemNumber2 { get; set; }
        public string AlternativeItemNumber3 { get; set; }
        //public string AssetAccntId { get; set; }
        public string AssetAccountName { get; set; }
        public object AverageUnitCost { get; set; }
        public string BasePartNumber { get; set; }
        public object BaseUomCode { get; set; }
        //public int BaseUomId { get; set; }
        public string BaseUomName { get; set; }
        //public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CARB { get; set; }
        //public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        //public string CogsAccntId { get; set; }
        public string SubCategoryName { get; set; }
        public string CogsAccountName { get; set; }
        public string CooCodeIso2 { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public object CurrencyCode { get; set; }
        public List<Currencypricelist> CurrencyPriceList { get; set; }
        public string CustomFieldH1 { get; set; }
        public string CustomFieldH10 { get; set; }
        public string CustomFieldH11 { get; set; }
        public string CustomFieldH12 { get; set; }
        public string CustomFieldH13 { get; set; }
        public string CustomFieldH14 { get; set; }
        public string CustomFieldH15 { get; set; }
        public string CustomFieldH16 { get; set; }
        public string CustomFieldH17 { get; set; }
        public string CustomFieldH18 { get; set; }
        public string CustomFieldH19 { get; set; }
        public string CustomFieldH2 { get; set; }
        public string CustomFieldH20 { get; set; }
        public string CustomFieldH21 { get; set; }
        public string CustomFieldH22 { get; set; }
        public string CustomFieldH23 { get; set; }
        public string CustomFieldH24 { get; set; }
        public string CustomFieldH25 { get; set; }
        public string CustomFieldH26 { get; set; }
        public string CustomFieldH27 { get; set; }
        public string CustomFieldH28 { get; set; }
        public string CustomFieldH29 { get; set; }
        public string CustomFieldH3 { get; set; }
        public string CustomFieldH30 { get; set; }
        public string CustomFieldH31 { get; set; }
        public string CustomFieldH32 { get; set; }
        public string CustomFieldH33 { get; set; }
        public string CustomFieldH34 { get; set; }
        public string CustomFieldH35 { get; set; }
        public string CustomFieldH36 { get; set; }
        public string CustomFieldH37 { get; set; }
        public string CustomFieldH38 { get; set; }
        public string CustomFieldH39 { get; set; }
        //[JsonPropertyName("customFieldH4")]
        public string CustomFieldH4 { get; set; }
        public string CustomFieldH40 { get; set; }
        public string CustomFieldH41 { get; set; }
        public string CustomFieldH42 { get; set; }
        public string CustomFieldH43 { get; set; }
        public string CustomFieldH44 { get; set; }
        public string CustomFieldH45 { get; set; }
        public string CustomFieldH46 { get; set; }
        public string CustomFieldH47 { get; set; }
        public string CustomFieldH48 { get; set; }
        public string CustomFieldH49 { get; set; }
        public string? CustomFieldH5 { get; set; }
        public string CustomFieldH50 { get; set; }
        public string? CustomFieldH6 { get; set; }
        public string CustomFieldH7 { get; set; }
        public string? CustomFieldH8 { get; set; }
        public string? CustomFieldH9 { get; set; }
        public decimal? CustomPrice1 { get; set; }
        public decimal? CustomPrice10 { get; set; }
        public decimal? CustomPrice11 { get; set; }
        public decimal? CustomPrice12 { get; set; }
        public decimal? CustomPrice13 { get; set; }
        public decimal? CustomPrice14 { get; set; }
        public decimal? CustomPrice2 { get; set; }
        public decimal? CustomPrice3 { get; set; }
        public decimal? CustomPrice4 { get; set; }
        public decimal? CustomPrice5 { get; set; }
        public decimal? CustomPrice6 { get; set; }
        public decimal? CustomPrice7 { get; set; }
        public decimal? CustomPrice8 { get; set; }
        public decimal? CustomPrice9 { get; set; }
        //public object CustomPriceFormula { get; set; }
        //public object CustomPriceLabels { get; set; }
        public string DefaultLocationClassName { get; set; }
        //public object DefaultLocationId { get; set; }
        public string DefaultLocationName { get; set; }
        //public object DefaultStoreId { get; set; }
        public string DefaultStoreName { get; set; }
        public object DefaultVendorId { get; set; }
        public string DefaultVendorName { get; set; }
        public string Description { get; set; }
        public object DiscontinuedDate { get; set; }
        public object DiscountedPrice { get; set; }
        public bool DoNotUpdateAccounts { get; set; }
        public bool DropShipItemFlag { get; set; }
        public object DropShipItemFlagStr { get; set; }
        public object DropShipVendors { get; set; }
        public object DropShipVendorsList { get; set; }
        //public string ExpenseAccntId { get; set; }
        public string ExpenseAccountName { get; set; }
        public object ExpirationDate { get; set; }
        public bool ForceSalesTaxCode { get; set; }
        public string ForceSalesTaxCodeStr { get; set; }
        public string GenderCode { get; set; }
        //public object GroupId { get; set; }
        public string GroupName { get; set; }
        public bool HasMultiCurPrice { get; set; }
        public string HazmatCode { get; set; }
        public object HazmatId { get; set; }
        public string HazmatName { get; set; }
        public object Height { get; set; }
        public object HomeCurrencyCode { get; set; }
        public string HSCode { get; set; }
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public string IncomeAccntId { get; set; }
        public string IncomeAccountName { get; set; }
        public string IncomeReturnAccountName { get; set; }
        public string IncomeReturnAccntId { get; set; }
        public bool IsBomItemFlag { get; set; }
        public bool IsPreSellFlag { get; set; }
        public string IsPreSellFlagStr { get; set; }
        public bool IsProducibleFlag { get; set; }
        public object IsProducibleFlagStr { get; set; }
        public bool IsPurchasableFlag { get; set; }
        public object IsPurchasableFlagStr { get; set; }
        public bool IsRawMaterialFlag { get; set; }
        public object IsRawMaterialFlagStr { get; set; }
        public bool ManufactureItemFlag { get; set; }
        public string ManufactureItemFlagStr { get; set; }
        public bool IsRestrictToPurchaseFlag { get; set; }
        public string IsRestrictToPurchaseFlagStr { get; set; }
        public bool IsSelected { get; set; }
        public bool IsSellableFlag { get; set; }
        public object IsSellableFlagStr { get; set; }
        public bool IsStockingItemFlag { get; set; }
        public bool IsTaxableOnPurchase { get; set; }
        public object IsTaxableOnPurchaseStr { get; set; }
        public bool IsTaxableOnSale { get; set; }
        public object IsTaxableOnSaleStr { get; set; }
        public bool IsTransferableFlag { get; set; }
        public string IsTransferableFlagStr { get; set; }
        public string ItemBarcode { get; set; }
        public object ItemBomJson { get; set; }
        public object ItemGtin { get; set; }
        public object[] ItemImageList { get; set; }
        public string ItemNumber { get; set; }
        public string ItemProductCategoryName { get; set; }
        public object ItemSalesForecastList { get; set; }
        public object[] ItemSalesTaxProvinceMapList { get; set; }
        public object ItemTrackingTypeId { get; set; }
        public object ItemTrackingTypeName { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemUpc { get; set; }
        public object Length { get; set; }
        public object Margin { get; set; }
        //public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public bool MultipleUomFlag { get; set; }
        public object Name { get; set; }
        public bool NeedsTrackingFlag { get; set; }
        public string OldItemNumber { get; set; }
        public string Option1Name { get; set; }
        public int Option1Seq { get; set; }
        public string Option1Value { get; set; }
        public string Option1ValueCode { get; set; }
        //public int Option1ValueId { get; set; }
        public string Option2Name { get; set; }
        public int Option2Seq { get; set; }
        public string Option2Value { get; set; }
        public string Option2ValueCode { get; set; }
        //public object Option2ValueId { get; set; }
        public string Option3Name { get; set; }
        public int Option3Seq { get; set; }
        public string Option3Value { get; set; }
        public string Option3ValueCode { get; set; }
        //public object Option3ValueId { get; set; }
        public object OptionArray { get; set; }
        public bool PriceNotAvailable { get; set; }
        //public int ProductCategoryId { get; set; }
        public int ProductHeaderId { get; set; }
        public object ProductImageId { get; set; }
        public object ProductImages { get; set; }
        public int? ProjectClassId { get; set; }
        public object ProjectClassName { get; set; }
        public string PurchaseNotes { get; set; }
        public string PurchaseTaxCode { get; set; }
        public object PurchaseTaxCodeId { get; set; }
        public string PurchaseTaxCodeName { get; set; }
        public object PurchaseUomCode { get; set; }
        public int PurchaseUomId { get; set; }
        public string PurchaseUomName { get; set; }
        public bool QtyDecimalFlag { get; set; }
        public bool ReadonlyFlag { get; set; }
        public bool ReCalculateCustomPrices { get; set; }
        public object ReCalculateCustomPricesStr { get; set; }
        public object RefId { get; set; }
        public bool RemoveImageFlag { get; set; }
        //public int ReOrderPointQty { get; set; }
        public object ReorderPointQtyList { get; set; }
        //public int ReOrderQty { get; set; }
        public object RestockingFeePer { get; set; }
        public bool ReturnableFlag { get; set; }
        public string ReturnableFlagStr { get; set; }
        public string SalesNotes { get; set; }
        //public int SalesTaxCodeId { get; set; }
        public string SaleTaxCode { get; set; }
        public string SaleTaxCodeName { get; set; }
        public string ScrapAccntId { get; set; }
        public string ScrapAccountName { get; set; }
        public object[] SeasonIdList { get; set; }
        public string SeasonValues { get; set; }
        public decimal? SellPkgQty { get; set; }
        public object SellUomCode { get; set; }
        public int SellUomId { get; set; }
        public string SellUomName { get; set; }
        public string ShelfLife { get; set; }
        public object SizeUomCode { get; set; }
        //public int SizeUomId { get; set; }
        public string SizeUomName { get; set; }
        public decimal? StandardUnitCost { get; set; }
        public decimal? StandardUnitPrice { get; set; }
        public string Tags { get; set; }
        public string TaxCategoryCode { get; set; }
        public object TaxStateMappingProfile { get; set; }
        public int TaxStateMappingProfileId { get; set; }
        public object ThirdPartyDisplayName { get; set; }
        public object ThirdPartyIconUrl { get; set; }
        public object ThirdPartyImageRefNo { get; set; }
        public string ThirdPartyRefNo { get; set; }
        public object ThirdPartySource { get; set; }
        public string Title { get; set; }
        public bool TrackingBySerialNumberFlag { get; set; }
        public object TrackingBySerialNumberFlagStr { get; set; }
        public object TxnTypeId { get; set; }
        public string UniqueId { get; set; }
        public bool UpdateDefaultItemImage { get; set; }
        public bool UseImageForProductPreviewFlag { get; set; }
        public object UseImageForProductPreviewFlagStr { get; set; }
        public string VariantInfo { get; set; }
        public string VariantInfoColored { get; set; }
        public object VelocityCodeId { get; set; }
        public string WarrantyTime { get; set; }
        public string WarrantyUOM { get; set; }
        public string WebUrl { get; set; }
        public float? Weight { get; set; }
        public object WeightUomCode { get; set; }
        //public int WeightUomId { get; set; }
        public string WeightUomName { get; set; }
        public object Width { get; set; }
        public string WipAccntId { get; set; }
        public string WipAccountName { get; set; }
    }

    public class Currencypricelist
    {
        public string CurrencyCode { get; set; }
        public int CurrencyId { get; set; }
        public decimal? CustomPrice1 { get; set; }
        public decimal? CustomPrice10 { get; set; }
        public object CustomPrice10Label { get; set; }
        public decimal? CustomPrice11 { get; set; }
        public object CustomPrice11Label { get; set; }
        public decimal? CustomPrice12 { get; set; }
        public object CustomPrice12Label { get; set; }
        public decimal? CustomPrice13 { get; set; }
        public object CustomPrice13Label { get; set; }
        public decimal? CustomPrice14 { get; set; }
        public object CustomPrice14Label { get; set; }
        public object CustomPrice1Label { get; set; }
        public decimal? CustomPrice2 { get; set; }
        public object CustomPrice2Label { get; set; }
        public decimal? CustomPrice3 { get; set; }
        public object CustomPrice3Label { get; set; }
        public decimal? CustomPrice4 { get; set; }
        public object CustomPrice4Label { get; set; }
        public decimal? CustomPrice5 { get; set; }
        public object CustomPrice5Label { get; set; }
        public decimal? CustomPrice6 { get; set; }
        public object CustomPrice6Label { get; set; }
        public decimal? CustomPrice7 { get; set; }
        public object CustomPrice7Label { get; set; }
        public decimal? CustomPrice8 { get; set; }
        public object CustomPrice8Label { get; set; }
        public decimal? CustomPrice9 { get; set; }
        public object CustomPrice9Label { get; set; }
        public bool DeleteFlag { get; set; }
        public bool EditState { get; set; }
        public int Id { get; set; }
        public object ImportError { get; set; }
        public int ItemId { get; set; }
        public string ItemNumber { get; set; }
        public object ReCalculateCustomPrices { get; set; }
        public decimal? StandardUnitCost { get; set; }
        public decimal? StandardUnitPrice { get; set; }
        public int UomId { get; set; }
        public string UomName { get; set; }
    }


    // Product Update Create Reponse
    public class XoroProductResponseA
    {
        public bool ConfirmFlag { get; set; }
        public object ConfirmValue { get; set; }
        public object ConfirmValueData { get; set; }
        public object Data { get; set; }
        public bool EndRequest { get; set; }
        public int ErrorCode { get; set; }
        public bool IsForwardRequest { get; set; }
        public bool LogFlag { get; set; }
        public string Message { get; set; }
        public object MessageTitle { get; set; }
        public string MetaData { get; set; }
        public bool Result { get; set; }
    }


    // Product Update Create Reponse A
    public class XoroProductRootobject
    {
        public bool ConfirmFlag { get; set; }
        public object ConfirmValue { get; set; }
        public object ConfirmValueData { get; set; }
        public Data4 Data { get; set; }
        public bool EndRequest { get; set; }
        public int ErrorCode { get; set; }
        public bool IsForwardRequest { get; set; }
        public bool LogFlag { get; set; }
        public string Message { get; set; }
        public object MessageTitle { get; set; }
        public string MetaData { get; set; }
        public bool Result { get; set; }
        public int SelectorErrorCode { get; set; }
    }

    public class Data4
    {
        public int Id { get; set; }
        public string BodyHtml { get; set; }
        public string Handle { get; set; }
        public string BasePartNumber { get; set; }
        public object CategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public string Title { get; set; }
        public Option4[] Options { get; set; }
        public bool ActiveFlag { get; set; }
        public string CreateDttm { get; set; }
        public object CreateSource { get; set; }
        public object ModifyDttm { get; set; }
        public object ModifySource { get; set; }
        public Variant4[] Variants { get; set; }
        public object ProductImages { get; set; }
        public object ProductTags { get; set; }
        public object DefaultProductImagePath { get; set; }
        public object ProductCustomizationProfile { get; set; }
        public bool IsHeaderOnly { get; set; }
    }

    public class Option4
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public string[] ValueArr { get; set; }
        public Value4[] Values { get; set; }
    }

    public class Value4
    {
        public string Code { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int OptionId { get; set; }
        public int Seq { get; set; }
    }

    public class Variant4
    {
        public object Account3PLCode { get; set; }
        public object Account3PLId { get; set; }
        public object Account3PLName { get; set; }
        public bool ActiveFlag { get; set; }
        public object ActiveFlagStr { get; set; }
        public string AdjAccntId { get; set; }
        public string AdjAccountName { get; set; }
        public string AlertNote { get; set; }
        public bool AllowBackorderFlag { get; set; }
        public object AllowedPurchaseUomIdList { get; set; }
        public object AllowedPurchaseUomNameList { get; set; }
        public object AllowedSellUomIdList { get; set; }
        public object AllowedSellUomNameList { get; set; }
        public string AlternativeItemNumber1 { get; set; }
        public string AlternativeItemNumber2 { get; set; }
        public string AlternativeItemNumber3 { get; set; }
        public string AssetAccntId { get; set; }
        public string AssetAccountName { get; set; }
        public bool AssignUPCs { get; set; }
        public object AverageUnitCost { get; set; }
        public string BasePartNumber { get; set; }
        public object BaseUomCode { get; set; }
        public int BaseUomId { get; set; }
        public string BaseUomName { get; set; }
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CARB { get; set; }
        public object CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CogsAccntId { get; set; }
        public string CogsAccountName { get; set; }
        public string CooCodeIso2 { get; set; }
        public object CooName { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public object CubicCapacity { get; set; }
        public object CubicCapacityUomCode { get; set; }
        public object CubicCapacityUomId { get; set; }
        public object CubicCapacityUomName { get; set; }
        public object CurrencyCode { get; set; }
        public Currencypricelist[] CurrencyPriceList { get; set; }
        public object CustomDescription { get; set; }
        public string CustomFieldH1 { get; set; }
        public string CustomFieldH10 { get; set; }
        public string CustomFieldH11 { get; set; }
        public string CustomFieldH12 { get; set; }
        public string CustomFieldH13 { get; set; }
        public string CustomFieldH14 { get; set; }
        public string CustomFieldH15 { get; set; }
        public string CustomFieldH16 { get; set; }
        public string CustomFieldH17 { get; set; }
        public string CustomFieldH18 { get; set; }
        public string CustomFieldH19 { get; set; }
        public string CustomFieldH2 { get; set; }
        public string CustomFieldH20 { get; set; }
        public string CustomFieldH21 { get; set; }
        public string CustomFieldH22 { get; set; }
        public string CustomFieldH23 { get; set; }
        public string CustomFieldH24 { get; set; }
        public string CustomFieldH25 { get; set; }
        public string CustomFieldH26 { get; set; }
        public string CustomFieldH27 { get; set; }
        public string CustomFieldH28 { get; set; }
        public string CustomFieldH29 { get; set; }
        public string CustomFieldH3 { get; set; }
        public string CustomFieldH30 { get; set; }
        public string CustomFieldH31 { get; set; }
        public string CustomFieldH32 { get; set; }
        public string CustomFieldH33 { get; set; }
        public string CustomFieldH34 { get; set; }
        public string CustomFieldH35 { get; set; }
        public string CustomFieldH36 { get; set; }
        public string CustomFieldH37 { get; set; }
        public string CustomFieldH38 { get; set; }
        public string CustomFieldH39 { get; set; }
        public string CustomFieldH4 { get; set; }
        public string CustomFieldH40 { get; set; }
        public string CustomFieldH41 { get; set; }
        public string CustomFieldH42 { get; set; }
        public string CustomFieldH43 { get; set; }
        public string CustomFieldH44 { get; set; }
        public string CustomFieldH45 { get; set; }
        public string CustomFieldH46 { get; set; }
        public string CustomFieldH47 { get; set; }
        public string CustomFieldH48 { get; set; }
        public string CustomFieldH49 { get; set; }
        public string CustomFieldH5 { get; set; }
        public string CustomFieldH50 { get; set; }
        public string CustomFieldH6 { get; set; }
        public string CustomFieldH7 { get; set; }
        public string CustomFieldH8 { get; set; }
        public string CustomFieldH9 { get; set; }
        public float CustomPrice1 { get; set; }
        public object CustomPrice10 { get; set; }
        public object CustomPrice11 { get; set; }
        public object CustomPrice12 { get; set; }
        public object CustomPrice13 { get; set; }
        public object CustomPrice14 { get; set; }
        public float CustomPrice2 { get; set; }
        public float CustomPrice3 { get; set; }
        public float CustomPrice4 { get; set; }
        public float CustomPrice5 { get; set; }
        public object CustomPrice6 { get; set; }
        public object CustomPrice7 { get; set; }
        public object CustomPrice8 { get; set; }
        public object CustomPrice9 { get; set; }
        public object CustomPriceFormula { get; set; }
        public object CustomPriceFormulaProfile { get; set; }
        public object CustomPriceFormulaProfileId { get; set; }
        public object CustomPriceLabels { get; set; }
        public string DefaultLocationClassName { get; set; }
        public object DefaultLocationId { get; set; }
        public string DefaultLocationName { get; set; }
        public object DefaultProductImagePath { get; set; }
        public object DefaultSkuImagePath { get; set; }
        public object DefaultStoreId { get; set; }
        public string DefaultStoreName { get; set; }
        public int? DefaultVendorId { get; set; }
        public string DefaultVendorName { get; set; }
        public string Description { get; set; }
        public object DescriptionSequence { get; set; }
        public object DiscontinuedDate { get; set; }
        public object DiscountedPrice { get; set; }
        public bool DoNotUpdateAccounts { get; set; }
        public bool DoNotUseCheckDBValidation { get; set; }
        public bool DropShipItemFlag { get; set; }
        public object DropShipItemFlagStr { get; set; }
        public object DropShipVendors { get; set; }
        public object DropShipVendorsList { get; set; }
        public string ExpenseAccntId { get; set; }
        public string ExpenseAccountName { get; set; }
        public object ExpirationDate { get; set; }
        public bool ForceSalesTaxCode { get; set; }
        public string ForceSalesTaxCodeStr { get; set; }
        public string GenderCode { get; set; }
        public object GroupId { get; set; }
        public string GroupName { get; set; }
        public object Handle { get; set; }
        public bool HasMultiCurPrice { get; set; }
        public string HazmatCode { get; set; }
        public object HazmatId { get; set; }
        public string HazmatName { get; set; }
        public object Height { get; set; }
        public object HomeCurrencyCode { get; set; }
        public string HSCode { get; set; }
        public object HSCodeId { get; set; }
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public object ImageUrls { get; set; }
        public object ImportError { get; set; }
        public string IncomeAccntId { get; set; }
        public string IncomeAccountName { get; set; }
        public string IncomeReturnAccntId { get; set; }
        public string IncomeReturnAccountName { get; set; }
        public float InnerCaseQty { get; set; }
        public object InnerCaseUPC { get; set; }
        public bool InventoryTabAccessPortalSubForm { get; set; }
        public bool Is3AItemFlag { get; set; }
        public bool IsBomItemFlag { get; set; }
        public bool IsPreSellFlag { get; set; }
        public string IsPreSellFlagStr { get; set; }
        public bool IsProducibleFlag { get; set; }
        public object IsProducibleFlagStr { get; set; }
        public bool IsPurchasableFlag { get; set; }
        public object IsPurchasableFlagStr { get; set; }
        public bool IsRawMaterialFlag { get; set; }
        public object IsRawMaterialFlagStr { get; set; }
        public bool IsRestrictToPurchaseFlag { get; set; }
        public string IsRestrictToPurchaseFlagStr { get; set; }
        public bool IsSelected { get; set; }
        public bool IsSellableFlag { get; set; }
        public object IsSellableFlagStr { get; set; }
        public bool IsStockingItemFlag { get; set; }
        public bool IsTaxableOnPurchase { get; set; }
        public object IsTaxableOnPurchaseStr { get; set; }
        public bool IsTaxableOnSale { get; set; }
        public object IsTaxableOnSaleStr { get; set; }
        public bool IsTransferableFlag { get; set; }
        public string IsTransferableFlagStr { get; set; }
        public string ItemBarcode { get; set; }
        public object ItemBomJson { get; set; }
        public object ItemGtin { get; set; }
        public object[] ItemImageList { get; set; }
        public object ItemLpnAttributeMappingObj { get; set; }
        public string ItemNumber { get; set; }
        public object ItemNumberSequence { get; set; }
        public string ItemProductCategoryName { get; set; }
        public object ItemSalesForecastList { get; set; }
        public object[] ItemSalesTaxProvinceMapList { get; set; }
        public object ItemTrackingTypeId { get; set; }
        public object ItemTrackingTypeName { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemUpc { get; set; }
        public object LastLandedUnitCost { get; set; }
        public object LastLandedUnitHomeCurrency { get; set; }
        public object LastPurchasedQty { get; set; }
        public object LastReceiptCurrencyCode { get; set; }
        public object LastReceiptDate { get; set; }
        public object LastReceiptReconcileFlag { get; set; }
        public object LastUnitCost { get; set; }
        public object LeadTimeDays { get; set; }
        public object Length { get; set; }
        public bool ManufactureItemFlag { get; set; }
        public object ManufactureItemFlagStr { get; set; }
        public object Manufacturer { get; set; }
        public object ManufacturerId { get; set; }
        public string Margin { get; set; }
        public float MasterCaseQty { get; set; }
        public object MasterCaseUPC { get; set; }
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public object MID { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public bool MultipleUomFlag { get; set; }
        public object Name { get; set; }
        public bool NeedsTrackingFlag { get; set; }
        public string OldItemNumber { get; set; }
        public string Option1Name { get; set; }
        public int Option1Seq { get; set; }
        public string Option1Value { get; set; }
        public string Option1ValueCode { get; set; }
        public int Option1ValueId { get; set; }
        public string Option2Name { get; set; }
        public int Option2Seq { get; set; }
        public string Option2Value { get; set; }
        public string Option2ValueCode { get; set; }
        public int Option2ValueId { get; set; }
        public string Option3Name { get; set; }
        public int Option3Seq { get; set; }
        public string Option3Value { get; set; }
        public string Option3ValueCode { get; set; }
        public object Option3ValueId { get; set; }
        public object OptionArray { get; set; }
        public bool PriceNotAvailable { get; set; }
        public object ProductCategoryId { get; set; }
        public bool ProductCustomizationExists { get; set; }
        public bool ProductCustomizationMandatory { get; set; }
        public object ProductCustomizationProfileId { get; set; }
        public object ProductCustomizationVasCost { get; set; }
        public object ProductCustomizationVasId { get; set; }
        public int ProductHeaderId { get; set; }
        public object ProductImageId { get; set; }
        public object ProductImages { get; set; }
        public object ProductTags { get; set; }
        public object ProjectClassId { get; set; }
        public object ProjectClassName { get; set; }
        public string PurchaseNotes { get; set; }
        public string PurchaseTaxCode { get; set; }
        public int PurchaseTaxCodeId { get; set; }
        public string PurchaseTaxCodeName { get; set; }
        public object PurchaseUomCode { get; set; }
        public int PurchaseUomId { get; set; }
        public string PurchaseUomName { get; set; }
        public bool QtyDecimalFlag { get; set; }
        public bool ReadonlyFlag { get; set; }
        public bool ReCalculateCustomPrices { get; set; }
        public object ReCalculateCustomPricesStr { get; set; }
        public object RefId { get; set; }
        public bool RemoveImageFlag { get; set; }
        public object ReOrderPointQty { get; set; }
        public object ReorderPointQtyList { get; set; }
        public object ReOrderQty { get; set; }
        public object RestockingFeePer { get; set; }
        public bool ReturnableFlag { get; set; }
        public string ReturnableFlagStr { get; set; }
        public string SalesNotes { get; set; }
        public int SalesTaxCodeId { get; set; }
        public string SaleTaxCode { get; set; }
        public string SaleTaxCodeName { get; set; }
        public string ScrapAccntId { get; set; }
        public string ScrapAccountName { get; set; }
        public object SearchKeywords { get; set; }
        public object[] SeasonIdList { get; set; }
        public string SeasonValues { get; set; }
        public float SellPkgQty { get; set; }
        public object SellUomCode { get; set; }
        public int SellUomId { get; set; }
        public string SellUomName { get; set; }
        public string ShelfLife { get; set; }
        public bool ShowItemPreviewSubForm { get; set; }
        public object SizeUomCode { get; set; }
        public int SizeUomId { get; set; }
        public string SizeUomName { get; set; }
        public float StandardUnitCost { get; set; }
        public float StandardUnitPrice { get; set; }
        public object SubCategoryId { get; set; }
        public object SubCategoryName { get; set; }
        public string Tags { get; set; }
        public string TaxCategoryCode { get; set; }
        public object TaxStateMappingProfile { get; set; }
        public int TaxStateMappingProfileId { get; set; }
        public object ThirdPartyDisplayName { get; set; }
        public object ThirdPartyIconUrl { get; set; }
        public object ThirdPartyImageRefNo { get; set; }
        public object ThirdPartyRefNo { get; set; }
        public object ThirdPartySource { get; set; }
        public string Title { get; set; }
        public bool TrackingBySerialNumberFlag { get; set; }
        public object TrackingBySerialNumberFlagStr { get; set; }
        public object TxnTypeId { get; set; }
        public string UniqueId { get; set; }
        public object UomFactor { get; set; }
        public bool UpdateDefaultItemImage { get; set; }
        public bool UpdatePastTransactionsFlag { get; set; }
        public object UpdatePastTransactionsFlagStr { get; set; }
        public bool UseImageForProductPreviewFlag { get; set; }
        public object UseImageForProductPreviewFlagStr { get; set; }
        public string VariantInfo { get; set; }
        public string VariantInfoColored { get; set; }
        public object VelocityCodeId { get; set; }
        public object VendorDiscount { get; set; }
        public object VendorListPrice { get; set; }
        public object VendorPartNumber { get; set; }
        public string WarrantyTime { get; set; }
        public string WarrantyUOM { get; set; }
        public string WebUrl { get; set; }
        public object Weight { get; set; }
        public string WeightUomCode { get; set; }
        public int WeightUomId { get; set; }
        public string WeightUomName { get; set; }
        public object Width { get; set; }
        public string WipAccntId { get; set; }
        public string WipAccountName { get; set; }
    }




    // Product Update Create Reponse C
    public class XoroProductRootobjectC
    {
        public bool ConfirmFlag { get; set; }
        public object ConfirmValue { get; set; }
        public object ConfirmValueData { get; set; }
        public Datum[] Data { get; set; }
        public bool EndRequest { get; set; }
        public int ErrorCode { get; set; }
        public bool IsForwardRequest { get; set; }
        public bool LogFlag { get; set; }
        public string Message { get; set; }
        public object MessageTitle { get; set; }
        public string MetaData { get; set; }
        public bool Result { get; set; }
        public int SelectorErrorCode { get; set; }
    }

    public class Datum
    {
        public int Id { get; set; }
        public string BodyHtml { get; set; }
        public string Handle { get; set; }
        public string BasePartNumber { get; set; }
        public object CategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public string Title { get; set; }
        public Option[] Options { get; set; }
        public bool ActiveFlag { get; set; }
        public string CreateDttm { get; set; }
        public object CreateSource { get; set; }
        public object ModifyDttm { get; set; }
        public object ModifySource { get; set; }
        public Variant[] Variants { get; set; }
        public object ProductImages { get; set; }
        public object ProductTags { get; set; }
        public object DefaultProductImagePath { get; set; }
        public object ProductCustomizationProfile { get; set; }
    }

    public class Option
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public string[] ValueArr { get; set; }
        public Value[] Values { get; set; }
    }

    public class Value
    {
        public string Code { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int OptionId { get; set; }
        public int Seq { get; set; }
    }

    public class Variant
    {
        public object Account3PLCode { get; set; }
        public object Account3PLId { get; set; }
        public object Account3PLName { get; set; }
        public bool ActiveFlag { get; set; }
        public object ActiveFlagStr { get; set; }
        public string AdjAccntId { get; set; }
        public string AdjAccountName { get; set; }
        public string AlertNote { get; set; }
        public bool AllowBackorderFlag { get; set; }
        public object AllowedPurchaseUomIdList { get; set; }
        public object AllowedPurchaseUomNameList { get; set; }
        public object AllowedSellUomIdList { get; set; }
        public object AllowedSellUomNameList { get; set; }
        public string AlternativeItemNumber1 { get; set; }
        public string AlternativeItemNumber2 { get; set; }
        public string AlternativeItemNumber3 { get; set; }
        public string AssetAccntId { get; set; }
        public string AssetAccountName { get; set; }
        public object AverageUnitCost { get; set; }
        public string BasePartNumber { get; set; }
        public object BaseUomCode { get; set; }
        public int BaseUomId { get; set; }
        public string BaseUomName { get; set; }
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CARB { get; set; }
        public object CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CogsAccntId { get; set; }
        public string CogsAccountName { get; set; }
        public string CooCodeIso2 { get; set; }
        public object CooName { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public object CubicCapacity { get; set; }
        public object CubicCapacityUomCode { get; set; }
        public object CubicCapacityUomId { get; set; }
        public object CubicCapacityUomName { get; set; }
        public object CurrencyCode { get; set; }
        public object[] CurrencyPriceList { get; set; }
        public object CustomDescription { get; set; }
        public string CustomFieldH1 { get; set; }
        public string CustomFieldH10 { get; set; }
        public string CustomFieldH11 { get; set; }
        public string CustomFieldH12 { get; set; }
        public string CustomFieldH13 { get; set; }
        public string CustomFieldH14 { get; set; }
        public string CustomFieldH15 { get; set; }
        public string CustomFieldH16 { get; set; }
        public string CustomFieldH17 { get; set; }
        public string CustomFieldH18 { get; set; }
        public string CustomFieldH19 { get; set; }
        public string CustomFieldH2 { get; set; }
        public string CustomFieldH20 { get; set; }
        public string CustomFieldH21 { get; set; }
        public string CustomFieldH22 { get; set; }
        public string CustomFieldH23 { get; set; }
        public string CustomFieldH24 { get; set; }
        public string CustomFieldH25 { get; set; }
        public string CustomFieldH26 { get; set; }
        public string CustomFieldH27 { get; set; }
        public string CustomFieldH28 { get; set; }
        public string CustomFieldH29 { get; set; }
        public string CustomFieldH3 { get; set; }
        public string CustomFieldH30 { get; set; }
        public string CustomFieldH31 { get; set; }
        public string CustomFieldH32 { get; set; }
        public string CustomFieldH33 { get; set; }
        public string CustomFieldH34 { get; set; }
        public string CustomFieldH35 { get; set; }
        public string CustomFieldH36 { get; set; }
        public string CustomFieldH37 { get; set; }
        public string CustomFieldH38 { get; set; }
        public string CustomFieldH39 { get; set; }
        public string CustomFieldH4 { get; set; }
        public string CustomFieldH40 { get; set; }
        public string CustomFieldH41 { get; set; }
        public string CustomFieldH42 { get; set; }
        public string CustomFieldH43 { get; set; }
        public string CustomFieldH44 { get; set; }
        public string CustomFieldH45 { get; set; }
        public string CustomFieldH46 { get; set; }
        public string CustomFieldH47 { get; set; }
        public string CustomFieldH48 { get; set; }
        public string CustomFieldH49 { get; set; }
        public string CustomFieldH5 { get; set; }
        public string CustomFieldH50 { get; set; }
        public string CustomFieldH6 { get; set; }
        public string CustomFieldH7 { get; set; }
        public string CustomFieldH8 { get; set; }
        public string CustomFieldH9 { get; set; }
        public float CustomPrice1 { get; set; }
        public object CustomPrice10 { get; set; }
        public object CustomPrice11 { get; set; }
        public object CustomPrice12 { get; set; }
        public object CustomPrice13 { get; set; }
        public object CustomPrice14 { get; set; }
        public float CustomPrice2 { get; set; }
        public float CustomPrice3 { get; set; }
        public float CustomPrice4 { get; set; }
        public float CustomPrice5 { get; set; }
        public object CustomPrice6 { get; set; }
        public object CustomPrice7 { get; set; }
        public object CustomPrice8 { get; set; }
        public object CustomPrice9 { get; set; }
        public object CustomPriceFormula { get; set; }
        public object CustomPriceFormulaProfile { get; set; }
        public object CustomPriceFormulaProfileId { get; set; }
        public object CustomPriceLabels { get; set; }
        public string DefaultLocationClassName { get; set; }
        public object DefaultLocationId { get; set; }
        public string DefaultLocationName { get; set; }
        public object DefaultProductImagePath { get; set; }
        public object DefaultSkuImagePath { get; set; }
        public object DefaultStoreId { get; set; }
        public string DefaultStoreName { get; set; }
        public int DefaultVendorId { get; set; }
        public string DefaultVendorName { get; set; }
        public string Description { get; set; }
        public object DescriptionSequence { get; set; }
        public object DiscontinuedDate { get; set; }
        public object DiscountedPrice { get; set; }
        public bool DoNotUpdateAccounts { get; set; }
        public bool DoNotUseCheckDBValidation { get; set; }
        public bool DropShipItemFlag { get; set; }
        public object DropShipItemFlagStr { get; set; }
        public object DropShipVendors { get; set; }
        public object DropShipVendorsList { get; set; }
        public string ExpenseAccntId { get; set; }
        public string ExpenseAccountName { get; set; }
        public object ExpirationDate { get; set; }
        public bool ForceSalesTaxCode { get; set; }
        public string ForceSalesTaxCodeStr { get; set; }
        public string GenderCode { get; set; }
        public object GroupId { get; set; }
        public string GroupName { get; set; }
        public bool HasMultiCurPrice { get; set; }
        public string HazmatCode { get; set; }
        public object HazmatId { get; set; }
        public string HazmatName { get; set; }
        public object Height { get; set; }
        public object HomeCurrencyCode { get; set; }
        public string HSCode { get; set; }
        public object HSCodeId { get; set; }
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public object ImageUrls { get; set; }
        public object ImportError { get; set; }
        public string IncomeAccntId { get; set; }
        public string IncomeAccountName { get; set; }
        public string IncomeReturnAccntId { get; set; }
        public string IncomeReturnAccountName { get; set; }
        public float InnerCaseQty { get; set; }
        public object InnerCaseUPC { get; set; }
        public bool InventoryTabAccessPortalSubForm { get; set; }
        public bool Is3AItemFlag { get; set; }
        public bool IsBomItemFlag { get; set; }
        public bool IsPreSellFlag { get; set; }
        public string IsPreSellFlagStr { get; set; }
        public bool IsProducibleFlag { get; set; }
        public object IsProducibleFlagStr { get; set; }
        public bool IsPurchasableFlag { get; set; }
        public object IsPurchasableFlagStr { get; set; }
        public bool IsRawMaterialFlag { get; set; }
        public object IsRawMaterialFlagStr { get; set; }
        public bool IsRestrictToPurchaseFlag { get; set; }
        public string IsRestrictToPurchaseFlagStr { get; set; }
        public bool IsSelected { get; set; }
        public bool IsSellableFlag { get; set; }
        public object IsSellableFlagStr { get; set; }
        public bool IsStockingItemFlag { get; set; }
        public bool IsTaxableOnPurchase { get; set; }
        public object IsTaxableOnPurchaseStr { get; set; }
        public bool IsTaxableOnSale { get; set; }
        public object IsTaxableOnSaleStr { get; set; }
        public bool IsTransferableFlag { get; set; }
        public string IsTransferableFlagStr { get; set; }
        public string ItemBarcode { get; set; }
        public object ItemBomJson { get; set; }
        public object ItemGtin { get; set; }
        public object[] ItemImageList { get; set; }
        public object ItemLpnAttributeMappingObj { get; set; }
        public string ItemNumber { get; set; }
        public object ItemNumberSequence { get; set; }
        public string ItemProductCategoryName { get; set; }
        public object ItemSalesForecastList { get; set; }
        public object[] ItemSalesTaxProvinceMapList { get; set; }
        public object ItemTrackingTypeId { get; set; }
        public object ItemTrackingTypeName { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemUpc { get; set; }
        public object LastLandedUnitCost { get; set; }
        public object LastLandedUnitHomeCurrency { get; set; }
        public object LastPurchasedQty { get; set; }
        public object LastReceiptCurrencyCode { get; set; }
        public object LastReceiptDate { get; set; }
        public object LastReceiptReconcileFlag { get; set; }
        public object LastUnitCost { get; set; }
        public object Length { get; set; }
        public bool ManufactureItemFlag { get; set; }
        public object ManufactureItemFlagStr { get; set; }
        public object Manufacturer { get; set; }
        public object ManufacturerId { get; set; }
        public object Margin { get; set; }
        public float MasterCaseQty { get; set; }
        public object MasterCaseUPC { get; set; }
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public object MID { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public bool MultipleUomFlag { get; set; }
        public object Name { get; set; }
        public bool NeedsTrackingFlag { get; set; }
        public string OldItemNumber { get; set; }
        public string Option1Name { get; set; }
        public int Option1Seq { get; set; }
        public string Option1Value { get; set; }
        public string Option1ValueCode { get; set; }
        public int Option1ValueId { get; set; }
        public string Option2Name { get; set; }
        public int Option2Seq { get; set; }
        public string Option2Value { get; set; }
        public string Option2ValueCode { get; set; }
        public int Option2ValueId { get; set; }
        public string Option3Name { get; set; }
        public int Option3Seq { get; set; }
        public string Option3Value { get; set; }
        public string Option3ValueCode { get; set; }
        public object Option3ValueId { get; set; }
        public object OptionArray { get; set; }
        public bool PriceNotAvailable { get; set; }
        public object ProductCategoryId { get; set; }
        public bool ProductCustomizationExists { get; set; }
        public bool ProductCustomizationMandatory { get; set; }
        public object ProductCustomizationProfileId { get; set; }
        public object ProductCustomizationVasCost { get; set; }
        public object ProductCustomizationVasId { get; set; }
        public int ProductHeaderId { get; set; }
        public object ProductImageId { get; set; }
        public object ProductImages { get; set; }
        public object ProductTags { get; set; }
        public object ProjectClassId { get; set; }
        public object ProjectClassName { get; set; }
        public string PurchaseNotes { get; set; }
        public string PurchaseTaxCode { get; set; }
        public int PurchaseTaxCodeId { get; set; }
        public string PurchaseTaxCodeName { get; set; }
        public object PurchaseUomCode { get; set; }
        public int PurchaseUomId { get; set; }
        public string PurchaseUomName { get; set; }
        public bool QtyDecimalFlag { get; set; }
        public bool ReadonlyFlag { get; set; }
        public bool ReCalculateCustomPrices { get; set; }
        public object ReCalculateCustomPricesStr { get; set; }
        public object RefId { get; set; }
        public bool RemoveImageFlag { get; set; }
        public object ReOrderPointQty { get; set; }
        public object ReorderPointQtyList { get; set; }
        public object ReOrderQty { get; set; }
        public object RestockingFeePer { get; set; }
        public bool ReturnableFlag { get; set; }
        public string ReturnableFlagStr { get; set; }
        public string SalesNotes { get; set; }
        public int SalesTaxCodeId { get; set; }
        public string SaleTaxCode { get; set; }
        public string SaleTaxCodeName { get; set; }
        public string ScrapAccntId { get; set; }
        public string ScrapAccountName { get; set; }
        public object SearchKeywords { get; set; }
        public object[] SeasonIdList { get; set; }
        public string SeasonValues { get; set; }
        public float SellPkgQty { get; set; }
        public object SellUomCode { get; set; }
        public int SellUomId { get; set; }
        public string SellUomName { get; set; }
        public string ShelfLife { get; set; }
        public bool ShowItemPreviewSubForm { get; set; }
        public object SizeUomCode { get; set; }
        public int SizeUomId { get; set; }
        public string SizeUomName { get; set; }
        public float StandardUnitCost { get; set; }
        public float StandardUnitPrice { get; set; }
        public object SubCategoryId { get; set; }
        public object SubCategoryName { get; set; }
        public string Tags { get; set; }
        public string TaxCategoryCode { get; set; }
        public object TaxStateMappingProfile { get; set; }
        public int TaxStateMappingProfileId { get; set; }
        public object ThirdPartyDisplayName { get; set; }
        public object ThirdPartyIconUrl { get; set; }
        public object ThirdPartyImageRefNo { get; set; }
        public object ThirdPartyRefNo { get; set; }
        public object ThirdPartySource { get; set; }
        public string Title { get; set; }
        public bool TrackingBySerialNumberFlag { get; set; }
        public object TrackingBySerialNumberFlagStr { get; set; }
        public object TxnTypeId { get; set; }
        public string UniqueId { get; set; }
        public object UomFactor { get; set; }
        public bool UpdateDefaultItemImage { get; set; }
        public bool UpdatePastTransactionsFlag { get; set; }
        public bool UseImageForProductPreviewFlag { get; set; }
        public object UseImageForProductPreviewFlagStr { get; set; }
        public string VariantInfo { get; set; }
        public string VariantInfoColored { get; set; }
        public object VelocityCodeId { get; set; }
        public string WarrantyTime { get; set; }
        public string WarrantyUOM { get; set; }
        public string WebUrl { get; set; }
        public object Weight { get; set; }
        public object WeightUomCode { get; set; }
        public int WeightUomId { get; set; }
        public string WeightUomName { get; set; }
        public object Width { get; set; }
        public string WipAccntId { get; set; }
        public string WipAccountName { get; set; }
    }






    // Product Update Create Reponse B
    public class XoroProductRootResponse
    {
        public bool ConfirmFlag { get; set; }
        public object ConfirmValue { get; set; }
        public object ConfirmValueData { get; set; }
        public List<ProductResponseDatum> Data { get; set; }
        public bool EndRequest { get; set; }
        public int ErrorCode { get; set; }
        public bool IsForwardRequest { get; set; }
        public bool LogFlag { get; set; }
        public string Message { get; set; }
        public object MessageTitle { get; set; }
        public string MetaData { get; set; }
        public bool Result { get; set; }
    }

    public class ProductResponseDatum
    {
        public int Id { get; set; }
        public string BodyHtml { get; set; }
        public string Handle { get; set; }
        public string BasePartNumber { get; set; }
        //public int CategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public string Title { get; set; }
        public List<ProductResponseOption> Options { get; set; }
        public bool ActiveFlag { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public List<object> Variants { get; set; }
        public object ProductImages { get; set; }
    }

    public class ProductResponseOption
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public List<string> ValueArr { get; set; }
        public List<ProductResponseValue> Values { get; set; }
    }

    public class ProductResponseValue
    {
        public string Code { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int OptionId { get; set; }
        public int Seq { get; set; }
    }

    public class ProductResponseVariant
    {
        public bool ActiveFlag { get; set; }
        public object ActiveFlagStr { get; set; }
        public string AdjAccntId { get; set; }
        public string AdjAccountName { get; set; }
        public string AlertNote { get; set; }
        public bool AllowBackorderFlag { get; set; }
        public string AlternativeItemNumber1 { get; set; }
        public string AlternativeItemNumber2 { get; set; }
        public string AlternativeItemNumber3 { get; set; }
        //public string AssetAccntId { get; set; }
        public string AssetAccountName { get; set; }
        public string BasePartNumber { get; set; }
        //public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CARB { get; set; }
        //public object CategoryId { get; set; }
        public string CategoryName { get; set; }
        //public string CogsAccntId { get; set; }
        public string CogsAccountName { get; set; }
        public string CooCodeIso2 { get; set; }
        public string CreateDttm { get; set; }
        public string CreateSource { get; set; }
        public object CurrencyCode { get; set; }
        //public object[] CurrencyPriceList { get; set; }
        public string CustomFieldH1 { get; set; }
        public string CustomFieldH10 { get; set; }
        public string CustomFieldH11 { get; set; }
        public string CustomFieldH12 { get; set; }
        public string CustomFieldH13 { get; set; }
        public string CustomFieldH14 { get; set; }
        public string CustomFieldH15 { get; set; }
        public string CustomFieldH16 { get; set; }
        public string CustomFieldH17 { get; set; }
        public string CustomFieldH18 { get; set; }
        public string CustomFieldH19 { get; set; }
        public string CustomFieldH2 { get; set; }
        public string CustomFieldH20 { get; set; }
        public string CustomFieldH21 { get; set; }
        public string CustomFieldH22 { get; set; }
        public string CustomFieldH23 { get; set; }
        public string CustomFieldH24 { get; set; }
        public string CustomFieldH25 { get; set; }
        public string CustomFieldH26 { get; set; }
        public string CustomFieldH27 { get; set; }
        public string CustomFieldH28 { get; set; }
        public string CustomFieldH29 { get; set; }
        public string CustomFieldH3 { get; set; }
        public string CustomFieldH30 { get; set; }
        public string CustomFieldH4 { get; set; }
        public string CustomFieldH5 { get; set; }
        public string CustomFieldH6 { get; set; }
        public string CustomFieldH7 { get; set; }
        public string CustomFieldH8 { get; set; }
        public string CustomFieldH9 { get; set; }
        public decimal? CustomPrice1 { get; set; }
        public decimal? CustomPrice10 { get; set; }
        public decimal? CustomPrice11 { get; set; }
        public decimal? CustomPrice12 { get; set; }
        public decimal? CustomPrice13 { get; set; }
        public decimal? CustomPrice14 { get; set; }
        public decimal? CustomPrice2 { get; set; }
        public decimal? CustomPrice3 { get; set; }
        public decimal? CustomPrice4 { get; set; }
        public decimal? CustomPrice5 { get; set; }
        public decimal? CustomPrice6 { get; set; }
        public decimal? CustomPrice7 { get; set; }
        public decimal? CustomPrice8 { get; set; }
        public decimal? CustomPrice9 { get; set; }
        public object CustomPriceLabels { get; set; }
        public string DefaultLocationClassName { get; set; }
        //public object DefaultLocationId { get; set; }
        public string DefaultLocationName { get; set; }
        public object DefaultStoreId { get; set; }
        public string DefaultStoreName { get; set; }
        //public object DefaultVendorId { get; set; }
        public string DefaultVendorName { get; set; }
        public string Description { get; set; }
        public object DiscountedPrice { get; set; }
        public bool DoNotUpdateAccounts { get; set; }
        public bool DropShipItemFlag { get; set; }
        //public string ExpenseAccntId { get; set; }
        public string ExpenseAccountName { get; set; }
        public object ExpirationDate { get; set; }
        public bool ForceSalesTaxCode { get; set; }
        public string ForceSalesTaxCodeStr { get; set; }
        public string GenderCode { get; set; }
        //public object GroupId { get; set; }
        public string GroupName { get; set; }
        public bool HasMultiCurPrice { get; set; }
        public string HazmatCode { get; set; }
        //public object HazmatId { get; set; }
        public string HazmatName { get; set; }
        public object Height { get; set; }
        public object HomeCurrencyCode { get; set; }
        public string HSCode { get; set; }
        //public int Id { get; set; }
        public string ImagePath { get; set; }
        //public string IncomeAccntId { get; set; }
        public string IncomeAccountName { get; set; }
        public string IncomeReturnAccountName { get; set; }
        public bool IsBomItemFlag { get; set; }
        public bool IsPreSellFlag { get; set; }
        public string IsPreSellFlagStr { get; set; }
        public bool IsPurchasableFlag { get; set; }
        public object IsPurchasableFlagStr { get; set; }
        public bool IsRawMaterialFlag { get; set; }
        public object IsRawMaterialFlagStr { get; set; }
        public bool IsSelected { get; set; }
        public bool IsSellableFlag { get; set; }
        public object IsSellableFlagStr { get; set; }
        public bool IsStockingItemFlag { get; set; }
        public bool IsTaxableOnPurchase { get; set; }
        public object IsTaxableOnPurchaseStr { get; set; }
        public bool IsTaxableOnSale { get; set; }
        public object IsTaxableOnSaleStr { get; set; }
        public bool IsTransferableFlag { get; set; }
        public string IsTransferableFlagStr { get; set; }
        public bool ManufactureItemFlag { get; set; }
        public string ManufactureItemFlagStr { get; set; }
        public string ItemBarcode { get; set; }
        public string ItemNumber { get; set; }
        public string ItemProductCategoryName { get; set; }
        //public object[] ItemSalesTaxProvinceMapList { get; set; }
        //public object ItemTrackingTypeId { get; set; }
        public object ItemTrackingTypeName { get; set; }
        //public int ItemTypeId { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemUpc { get; set; }
        public object Length { get; set; }
        public string Margin { get; set; }
        //public object MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string ModifyDttm { get; set; }
        public string ModifySource { get; set; }
        public bool MultipleUomFlag { get; set; }
        public object Name { get; set; }
        public bool NeedsTrackingFlag { get; set; }
        public string OldItemNumber { get; set; }
        public string Option1Name { get; set; }
        public int Option1Seq { get; set; }
        public string Option1Value { get; set; }
        public string Option1ValueCode { get; set; }
        //public int Option1ValueId { get; set; }
        public string Option2Name { get; set; }
        public int Option2Seq { get; set; }
        public string Option2Value { get; set; }
        public string Option2ValueCode { get; set; }
        //public int Option2ValueId { get; set; }
        public string Option3Name { get; set; }
        public int Option3Seq { get; set; }
        public string Option3Value { get; set; }
        public string Option3ValueCode { get; set; }
        //public object Option3ValueId { get; set; }
        public object OptionArray { get; set; }
        public bool PriceNotAvailable { get; set; }
        //public object ProductCategoryId { get; set; }
        //public int ProductHeaderId { get; set; }
        //public object ProductImageId { get; set; }
        public object ProductImages { get; set; }
        //public object ProjectClassId { get; set; }
        public object ProjectClassName { get; set; }
        public string PurchaseNotes { get; set; }
        public string PurchaseTaxCode { get; set; }
        public object PurchaseTaxCodeId { get; set; }
        public string PurchaseTaxCodeName { get; set; }
        public bool QtyDecimalFlag { get; set; }
        public bool ReadonlyFlag { get; set; }
        //public object RefId { get; set; }
        public bool RemoveImageFlag { get; set; }
        public int ReOrderPointQty { get; set; }
        public object ReorderPointQtyList { get; set; }
        public int ReOrderQty { get; set; }
        public object RestockingFeePer { get; set; }
        public bool ReturnableFlag { get; set; }
        public string ReturnableFlagStr { get; set; }
        public string SalesNotes { get; set; }
        //public int SalesTaxCodeId { get; set; }
        public string SaleTaxCode { get; set; }
        public string SaleTaxCodeName { get; set; }
        //public string ScrapAccntId { get; set; }
        public string ScrapAccountName { get; set; }
        //public object[] SeasonIdList { get; set; }
        public string SeasonValues { get; set; }
        public decimal? SellPkgQty { get; set; }
        public object SellUomCode { get; set; }
        //public int SellUomId { get; set; }
        public string SellUomName { get; set; }
        public string ShelfLife { get; set; }
        public object SizeUomCode { get; set; }
        //public int SizeUomId { get; set; }
        public string SizeUomName { get; set; }
        public float StandardUnitCost { get; set; }
        public float StandardUnitPrice { get; set; }
        public string Tags { get; set; }
        public object ThirdPartyImageRefNo { get; set; }
        public string Title { get; set; }
        //public object TxnTypeId { get; set; }
        public bool UseImageForProductPreviewFlag { get; set; }
        public object UseImageForProductPreviewFlagStr { get; set; }
        public string VariantInfo { get; set; }
        public string VariantInfoColored { get; set; }
        public object VelocityCodeId { get; set; }
        public string WarrantyTime { get; set; }
        public string WarrantyUOM { get; set; }
        public string WebUrl { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public float Weight { get; set; }
        public object WeightUomCode { get; set; }
        //public int WeightUomId { get; set; }
        public string WeightUomName { get; set; }
        public object Width { get; set; }
        //public string WipAccntId { get; set; }
        public string WipAccountName { get; set; }
    }
}
